# permissions for end users to view secretmanages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretmanage-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: middleware-operator
    app.kubernetes.io/part-of: middleware-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretmanage-viewer-role
rules:
- apiGroups:
  - middleware.workshop-operator.com
  resources:
  - secretmanages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - middleware.workshop-operator.com
  resources:
  - secretmanages/status
  verbs:
  - get
